import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Ekhon Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-full flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}